/*
 *  Copyright (c) 2010 Filippo Bua
 *  Copyright (c) 2010 Maurizio Paone
 *  Copyright (c) 2010 Francesco Tusa
 *  Copyright (c) 2010 Massimo Villari
 *  Copyright (c) 2010 Antonio Celesti
 *  Copyright (c) 2010 Antonio Nastasi
 *
 *  Permission is hereby granted, free of charge, to any person
 *  obtaining a copy of this software and associated documentation
 *  files (the "Software"), to deal in the Software without
 *  restriction, including without limitation the rights to use,
 *  copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the
 *  Software is furnished to do so, subject to the following
 *  conditions:
 *
 *  The above copyright notice and this permission notice shall be
 *  included in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 *  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 *  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 *  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 *  OTHER DEALINGS IN THE SOFTWARE.
 */

package org.clever.Common.VEInfo;

public class NetworkSettings {

    public static enum NetworkType {BRIDGED, LOCAL, NAT};
    private String mac;
    private int speed;
    private NetworkType type;
    
    public NetworkSettings(){
        
    }
    
    //Per VMWare
    private String netName;
    private String nicName;
    //MAC Address Type. generated: MAC address generated by the host; manual: if you want to specify MAC address; assigned: MAC address assigned by VirtualCenter
    public static enum MacAddressType {generated, manual, assigned}; //MAC ADDRESS TYPE
    private MacAddressType macAddrType;
    private boolean connected;
    private boolean startConnected;
    
    public NetworkSettings(String mac, int speed, NetworkType type){
        this.mac = mac;
        this.speed = speed;
        this.type = type;

    }
    
    //Per VMWare
    public NetworkSettings(String netName, String nicName, MacAddressType addrType){
        this.netName = netName;
        this.nicName = nicName;
        this.macAddrType = addrType;
    }
    public NetworkSettings(MacAddressType addrType){
        this.macAddrType = addrType;
    }

    
    public String getMac(){
        return (mac);

    }

    public void setMac(String value){
        mac = value;
    }

    public int getSpeed(){

        return speed;
    }

    public void setSpeed(int value){
        speed = value;

    }

    public NetworkType getType(){

        return type;
    }

    public void setType(NetworkType value){

        type = value;
    }
    
    
    //Per VMWare
    public void setNetName(String netName){
        this.netName = netName;
    }
    public String getNetName(){
        return this.netName;
    }
    public void setNicName(String nitName){
        this.nicName = nitName;
    }    
    public String getNicName(){
        return this.nicName;
    }
    public void setAddressType(MacAddressType addrType){
        this.macAddrType = addrType;
    }
    public MacAddressType getAddressType(){
        return this.macAddrType;
    }
    public void setConnected(boolean value){
        this.connected = value;
    }
    public boolean isConnected(){
        return this.connected;
    }
    public void setStartConnected(boolean value){
        this.startConnected = value;
    }
    public boolean isStartConnected(){
        return this.startConnected;
    }

}
